<?php use \dawfony\Ti; ?>
<?php Ti::extend("view/MainView.phtml"); ?>
<?php Ti::startBlock("content"); ?>
<div class="row">
		<div class="col-md-12">
			<form role="form" action="crearPost" method="POST" enctype="multipart/form-data" id="formularioPost">
				<div class="form-group">
					<label for="resumen">
						Titulo del Post:
					</label>
					<input type="text" class="form-control" id="resumen" name="resumen" />
				</div>
				<div class="form-group">
					<label for="texto">
						Texto del post
					</label><br>
                    <textarea name="texto" id="texto" cols="40" rows="3"></textarea>
				</div>
				<div class="form-group">
					<label for="categoriaPost">Categoría del Post</label>
					<select class="form-control" id="categoriaPost" name="categoriaPost">
						<?php foreach ($data["categoriasPosts"] as $value) { ?>
							<option class="categoriasPosts" value="<?= $value["descripcion"] ?>"><?= $value["descripcion"] ?></option>
						<?php } ?>
					</select>
				</div>
				<div class="form-group">
					<label for="foto">
						Imagen del Post
					</label>
					<input type="file" class="form-control-file" id="foto" name="foto" />
				</div>
				<button type="submit" class="btn btn-primary" id="subirPost">
					Subir
				</button>
			</form>
		</div>
	</div>
	<script>
		var categoriasPosts = '<?= json_encode($data["categoriasPosts"]) ?>';
	</script>
	<script src="js/comprobarPost.js"></script>
<?php Ti::endBlock(); ?>
<?php Ti::endExtend() ?>