<?php use \dawfony\Ti; ?>
<?php Ti::extend("view/MainView.phtml"); ?>
<?php Ti::startBlock("content"); ?>
<?php
    extract($data[])
?>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<dl>
				<dt>
					Login de usuario:
				</dt>
				<dd>
					<?= $datosUsuario->login ?>
				</dd>
				<dt>
					Nombre de usuario
				</dt>
				<dd>
                    <?= $datosUsuario->nombre ?>
				</dd>
				<dt>
					E-mail de usuario
				</dt>
				<dd>
                    <?= $datosUsuario->email ?>
				</dd>
				<dt>
					Posts:
				</dt>
			</dl>
		</div>
	</div>
</div>
<?php Ti::endBlock(); ?>
<?php Ti::endExtend() ?>