<?php use \dawfony\Ti; ?>
<?php Ti::extend("view/MainView.phtml"); ?>
<?php Ti::startBlock("content"); ?>
<?php
	extract($data["datos"]);
?>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<dl>
				<dt>
					Login de usuario:
				</dt>
				<dd>
					<?= $datosUsuario->login ?>
				</dd>
				<dt>
					Nombre de usuario
				</dt>
				<dd>
                    <?= $datosUsuario->nombre ?>
				</dd>
				<dt>
					E-mail de usuario
				</dt>
				<dd>
                    <?= $datosUsuario->email ?>
				</dd>
				<dt>
					Posts:
				</dt>
			</dl>
		</div>
        <?php if (isset($data["esBuscado"]) && isset($_SESSION["login"])) : ?>
        <div>
            <button type="button" class="btn btn-success">
				Seguir
			</button>
        </div>
        <?php endif ?>
	</div>
</div>
<?php
    foreach ($postsUsuario as $value) {
        ?>
            <div class="row">
            <div class="col-md-12">
                <div class="row unPost">
                    <div class="col-md-3">
                        <img class="iconoUsuario" alt="<?= $value->foto ?>" 
						src="<?php global $URL_PATH; echo $URL_PATH; ?>/assets/img/<?= $value->foto ?>" />
                    </div>
                    <div class="col-md-7">
                        <h2>
                            <?= $value->resumen ?>
                        </h2>
                        <p>
                        <?= $value->texto ?>
                        </p>
                        <p>
                            <a class="btn" href="#">View details »</a>
                        </p>
                    </div>
                    <div class="col-md-2">
                        <h2>
                            Por: <i><?= $value->usuario_login ?></i>
                        </h2>
                        <p>
                            de <strong><?= $value->categoria_post_id ?></strong>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <?php
    }
?>
<?php Ti::endBlock(); ?>
<?php Ti::endExtend() ?>