<?php use \dawfony\Ti; ?>
<?php Ti::extend("view/MainView.phtml"); ?>
<?php Ti::startBlock("content"); ?>
<?php
	extract($data["datos"]);
?>
<?php
    global $URL_PATH;
    ?>
    <script> var URL_PATH = "<?= $URL_PATH ?>" </script>
    <script src="<?= $URL_PATH ?>/js/likes.js"></script>
    <script src="<?= $URL_PATH ?>/js/cantidadComentarios.js"></script>
<div class="container-fluid">
	<div class="row colocarHorizontal">
		<div class="col-md-12">
			<dl>
				<dt>
					Login de usuario:
				</dt>
				<dd>
					<?= $datosUsuario->login ?>
				</dd>
				<dt>
					Nombre de usuario
				</dt>
				<dd>
                    <?= $datosUsuario->nombre ?>
				</dd>
				<dt>
					E-mail de usuario
				</dt>
				<dd>
                    <?= $datosUsuario->email ?>
				</dd>
				<dt>
					Posts:
				</dt>
			</dl>
		</div>
        <?php if ((isset($data["leSigue"]) && isset($_SESSION["login"])) && $_SESSION["login"] !== $data["usuario"] ) : ?>
            <?php if (!$data["leSigue"]){?>
        <div>
            <a class="btn btn-primary" href="seguirUsuario/<?= $datosUsuario->login ?>" role="button">Seguir</a>
        </div>
            <?php } elseif($data["leSigue"]) { ?>
                <div>
                    <a class="btn btn-danger" href="seguirUsuario/<?= $datosUsuario->login ?>" role="button">Dejar de seguir</a>
                </div>
            <?php } ?>
        <?php endif ?>
	</div>
</div>
<?php
    foreach ($postsUsuario as $value) {
        ?>
            <div class="row">
            <div class="col-md-12">
                <div class="row unPost">
                    <div class="col-md-3">
                        <img class="iconoUsuario" alt="<?= $value->foto ?>" 
						src="<?php global $URL_PATH; echo $URL_PATH; ?>/assets/img/<?= $value->foto ?>" />
                    </div>
                    <div class="col-md-7">
                        <h2>
                            <?= $value->resumen ?>
                        </h2>
                        <p>
                        <?= $value->texto ?>
                        </p>
                        <p>
                            <a class="btn" href="<?= $URL_PATH ?>/verPost/<?= $value->id ?>">Ver post »</a>
                        </p>
                        <p class="iconicos">
                            <img class="likes" id="<?= $value->id ?>" src="<?= $URL_PATH ?>/js/like.jpg" alt="like.jpg">
                            <span id="cantidadLikes<?= $value->id ?>"></span> 
                        </p>
                        <p class="iconicos">
                            <img class="comentariosIcono" src="<?= $URL_PATH ?>/js/comentarios.jpg" alt="comentarios.jpg">
                            <span class="comentarios" id="cantidadComentarios_<?= $value->id ?>"></span>
                        </p>
                    </div>
                    <div class="col-md-2">
                        <h2>
                            Por: <i><?= $value->usuario_login ?></i>
                        </h2>
                        <p>
                            de <strong><?= $value->categoria_post_id ?></strong><br>
                            en <?= $value->fecha ?>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <?php
    }
?>
<?php Ti::endBlock(); ?>
<?php Ti::endExtend() ?>