<?php use \dawfony\Ti; ?>
<?php Ti::extend("view/MainView.phtml"); ?>
<?php Ti::startBlock("content"); ?>
<?php
    extract($data["datos"]);
?>
<?php
    global $URL_PATH;
    ?>
    <script> var URL_PATH = "<?= $URL_PATH ?>" </script>
    <script src="<?= $URL_PATH ?>/js/likes.js"></script>
<div class="row">
            <div class="col-md-12">
                <div class="row unPost">
                    <div class="col-md-3">
                        <img class="iconoUsuario" alt="<?= $postUsuario->foto ?>" 
						src="<?php global $URL_PATH; echo $URL_PATH; ?>/assets/img/<?= $postUsuario->foto ?>" />
                    </div>
                    <div class="col-md-7">
                        <h2>
                            <?= $postUsuario->resumen ?>
                        </h2>
                        <p>
                        <?= $postUsuario->texto ?>
                        </p>
                        <p>
                            <img class="likes" id="<?= $postUsuario->id ?>" src="<?= $URL_PATH ?>/js/like.jpg" alt="like.jpg">
                            <span id="cantidadLikes<?= $postUsuario->id ?>"></span> 
                        </p>
                    </div>
                    <div class="col-md-2">
                        <h2>
                            Por: <i><?= $postUsuario->usuario_login ?></i>
                        </h2>
                        <p>
                            de <strong><?= $postUsuario->categoria_post_id ?></strong>
                        </p>
                    </div>
                </div>
            </div>
        </div>
<?php Ti::endBlock(); ?>
<?php Ti::endExtend() ?>