<?php use \dawfony\Ti; ?>
<?php Ti::extend("view/MainView.phtml"); ?>
<?php Ti::startBlock("content"); ?>
<?php
    $error = $data["error"] ?? false;
    if (isset($data["datosUsuario"])){
      extract($data["datosUsuario"]);
    }
    $existeUsuario = $data["existeUsuario"] ?? false;
?>
<form method="POST" action="registro">
    Registrate
    <?php if ($existeUsuario) : ?>
  <div class="alert alert-danger" role="alert">
    El usuario ya existe! Por favor, intenta utilizar otro
  </div>
  <?php endif ?>
  <div class="form-group">
    <label for="login">Login:</label>
    <input type="text" class="form-control" id="login" name="login" value="<?= $login ?? "" ?>">
    <?php if ($error) : ?>
    <small id="emailHelp" class="form-text text-muted">Introduce un login con el que identificarte</small>
    <?php endif ?>
  </div>
  <div class="form-group">
    <label for="password">Contraseña:</label>
    <input type="password" class="form-control" id="password" name="password" value="<?= $password ?? "" ?>">
    <?php if ($error) : ?>
    <small id="emailHelp" class="form-text text-muted">Introduce una contraseña</small>
    <?php endif ?>
  </div>
  <div class="form-group">
    <label for="passwordRepeat">Repite contraseña:</label>
    <input type="password" class="form-control" id="passwordRepeat"  name="passwordRepeat">
    <?php if ($error) : ?>
    <small id="emailHelp" class="form-text text-muted">Repite la contraseña o contraseñas no identicas</small>
    <?php endif ?>
  </div>
  <div class="form-group">
    <label for="nombre">Tu nombre:</label>
    <input type="text" class="form-control" id="nombre" name="nombre" value="<?= $nombre ?? "" ?>">
    <?php if ($error) : ?>
    <small id="emailHelp" class="form-text text-muted">Introduce tu nombre</small>
    <?php endif ?>
  </div>
  <div class="form-group">
    <label for="email">E-mail:</label>
    <input type="email" class="form-control" id="email" name="email" value="<?= $email ?? "" ?>">
    <?php if ($error) : ?>
    <small id="emailHelp" class="form-text text-muted">Introduce un e-mail</small>
    <?php endif ?>
  </div>
  <button type="submit" class="btn btn-primary">Registrarse</button>
</form>
<?php Ti::endBlock(); ?>
<?php Ti::endExtend() ?>