<?php use \dawfony\Ti; ?>
<?php Ti::extend("view/MainView.phtml"); ?>
<?php Ti::startBlock("content"); ?>
<div class="row">
		<div class="col-md-12">
			<div class="jumbotron">
				<h2>
					Usuario creado correctamente!
				</h2>
				<p>
					Pulsa aqui para iniciar sesion!
				</p>
				<p>
					<a class="btn btn-primary btn-large" href="login">Iniciar sesion</a>
				</p>
			</div>
		</div>
	</div>
<?php Ti::endBlock(); ?>
<?php Ti::endExtend() ?>